name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build solution
      run: msbuild /m /p:Platform=x64 YourSolution.sln

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: x64-artifacts
        path: |
          ${{github.workspace}}\bin\*-x64\**\*.dll
          ${{github.workspace}}\bin\*-x64\**\*.exe
          ${{github.workspace}}\bin\*-x64\**\*.lib
          ${{github.workspace}}\bin\*-x64\obj\**\*
        if-no-files-found: error